import 'package:flutter/material.dart';

class LocalizationService {
  static final LocalizationService _instance = LocalizationService._internal();
  factory LocalizationService() => _instance;
  LocalizationService._internal();

  Locale _currentLocale = const Locale('fr');
  Locale get currentLocale => _currentLocale;

  final Map<String, Map<String, String>> _localizedValues = {
    'fr': {
      'app_title': 'EEUEZ Menu',
      'tagline': 'L\'Expertise Digitale de Branche',
      'mode_client': 'Mode Client',
      'mode_merchant': 'Mode Dashboard',
      'mode_delivery': 'Mode Livreur',
      'order_meals': 'Commandez vos repas',
      'manage_resto': 'Gérer mon restaurant',
      'deliver_orders': 'Livrer des commandes',
      'welcome_msg': 'Savourez le meilleur\nde Douala',
      'delivery_tag': 'Livré chez vous en un éclair ⚡',
      'search_hint': 'Un plat, un restaurant...',
      'popular_restos': 'Restaurants Populaires',
      'see_all': 'Voir tout',
      'home': 'Accueil',
      'orders': 'Commandes',
      'favorites': 'Favoris',
      'profile': 'Profil',
      'cancel': 'Annuler',
      'delete': 'Supprimer',
      'add_to_cart': 'Ajouter au panier',
      'checkout': 'Acheter',
      'total': 'TOTAL',
      'confirm_payment': 'Confirmer le paiement',
      'certified': 'Certifié',
      'expert': 'Expert',
      'menu': 'Menu',
      'popular': 'Populaires',
      'tradition': 'Tradition',
      'drinks': 'Boissons',
      'sides': 'Accompagnements',
      'view_cart': 'Voir mon panier',
      'currency': 'FCFA',
      'dashboard': 'Tableau de Bord',
      'hr_mgmt': 'Gestion RH',
      'finance': 'Finance',
      'support': 'Support Client',
      'monitoring': 'Monitoring Flux',
      'logout_merchant': 'Quitter Mode Merchant',
      'pending_orders': 'Commandes en attente',
      'ready_delivery': 'Prêt pour livraison',
      'daily_sales': 'Ventes / Jour',
      'active_cmds': 'Cmd. Actives',
      'admin_badge': 'ADMINISTRATEUR',
      'online': 'En Ligne',
      'offline': 'Hors Ligne',
      'offline_msg': 'Vous êtes hors ligne',
      'offline_sub': 'Activez le service pour recevoir des courses',
      'available_trips': 'Courses Disponibles',
      'active_trip': 'Course en Cours',
      'accept': 'Accepter',
      'call': 'Appeler',
      'finish_trip': 'Terminer la course',
      'trip_completed': 'Course terminée',
      'view_tracking': 'Suivre ma commande',
      'waiting_for_trip': 'Recherche d\'une course...',
      'waiting_for_deliverer': 'Recherche d\'un livreur...',
      'deliverer_arrived': 'Le livreur est devant chez vous !',
      'status_accepted': 'Commande acceptée',
      'status_transit': 'En route vers vous',
      'status_arrived': 'Livreur devant chez vous',
      'validate_invoice': 'Valider la facture',
      'qr_msg': 'Scannez pour valider la course',
      'qr_sub': 'Le scan confirme la fin de la prestation.',
    },
    'en': {
      'app_title': 'EEUEZ Menu',
      'tagline': 'Digital Branch Expertise',
      'mode_client': 'Client Mode',
      'mode_merchant': 'Dashboard Mode',
      'mode_delivery': 'Deliverer Mode',
      'order_meals': 'Order your meals',
      'manage_resto': 'Manage my restaurant',
      'deliver_orders': 'Deliver orders',
      'welcome_msg': 'Savor the best\of Douala',
      'delivery_tag': 'Delivered to you in a flash ⚡',
      'search_hint': 'A dish, a restaurant...',
      'popular_restos': 'Popular Restaurants',
      'see_all': 'See all',
      'home': 'Home',
      'orders': 'Orders',
      'favorites': 'Favorites',
      'profile': 'Profile',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'add_to_cart': 'Add to cart',
      'checkout': 'Checkout',
      'total': 'TOTAL',
      'confirm_payment': 'Confirm payment',
      'certified': 'Certified',
      'expert': 'Expert',
      'menu': 'Menu',
      'popular': 'Popular',
      'tradition': 'Tradition',
      'drinks': 'Drinks',
      'sides': 'Sides',
      'view_cart': 'View my cart',
      'currency': 'FCFA',
      'dashboard': 'Dashboard',
      'hr_mgmt': 'HR Management',
      'finance': 'Finance',
      'support': 'Customer Support',
      'monitoring': 'Flow Monitoring',
      'logout_merchant': 'Exit Merchant Mode',
      'pending_orders': 'Pending Orders',
      'ready_delivery': 'Ready for delivery',
      'daily_sales': 'Daily Sales',
      'active_cmds': 'Active Orders',
      'admin_badge': 'ADMINISTRATOR',
      'online': 'Online',
      'offline': 'Offline',
      'offline_msg': 'You are offline',
      'offline_sub': 'Enable service to receive trips',
      'available_trips': 'Available Trips',
      'active_trip': 'Active Trip',
      'accept': 'Accept',
      'call': 'Call',
      'finish_trip': 'Finish Trip',
      'trip_completed': 'Trip completed',
      'view_tracking': 'Track my order',
      'waiting_for_trip': 'Searching for a trip...',
      'waiting_for_deliverer': 'Searching for a deliverer...',
      'deliverer_arrived': 'The deliverer is at your door!',
      'status_accepted': 'Order accepted',
      'status_transit': 'On the way to you',
      'status_arrived': 'Deliverer arrived at your door',
      'validate_invoice': 'Validate Invoice',
      'qr_msg': 'Scan to validate the trip',
      'qr_sub': 'Scanning confirms the service is complete.',
    },
  };

  String translate(String key) {
    return _localizedValues[_currentLocale.languageCode]?[key] ?? key;
  }

  void toggleLanguage() {
    _currentLocale = _currentLocale.languageCode == 'fr' 
        ? const Locale('en') 
        : const Locale('fr');
  }
}

// Global helper for easy access
String t(String key) => LocalizationService().translate(key);
