# Generated by Django 5.2.2 on 2026-06-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='delai_estime',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='frais_livraison',
            field=models.DecimalField(decimal_places=0, default=500, max_digits=10),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='temps_livraison_moyen',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='user',
            name='gain_total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='user',
            name='nombre_livraisons',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
