# Generated by Django 5.2.2 on 2026-07-06 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_abonnement_favori'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allergies',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='core.plat')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='core.restaurantprofile')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-updated_at'],
                'unique_together': {('client', 'plat')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('client', 'Client'), ('restaurant', 'Restaurant')], max_length=12)),
                ('texte', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.conversation')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plats/')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.plat')),
            ],
            options={
                'verbose_name': 'Photo de plat',
                'verbose_name_plural': 'Photos de plats',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlatNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_plats', to=settings.AUTH_USER_MODEL)),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.plat')),
            ],
            options={
                'verbose_name': 'Note de plat',
                'verbose_name_plural': 'Notes de plats',
                'unique_together': {('client', 'plat')},
            },
        ),
    ]
