# Generated by Django 5.2.2 on 2026-07-06 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_allergies_conversation_message_platimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetraitFonds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('mode_paiement', models.CharField(choices=[('mtn_money', 'MTN Money'), ('orange_money', 'Orange Money'), ('carte', 'Carte Bancaire'), ('especes', 'Espèces')], default='mtn_money', max_length=20)),
                ('numero_compte', models.CharField(blank=True, max_length=50)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('paye', 'Payé'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retraits', to='core.restaurantprofile')),
            ],
            options={
                'verbose_name': 'Retrait de fonds',
                'verbose_name_plural': 'Retraits de fonds',
                'ordering': ['-created_at'],
            },
        ),
    ]
