# Generated by Django 5.2.2 on 2026-07-06 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_retraitfonds'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='restaurant_attache',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livreurs', to='core.restaurantprofile'),
        ),
    ]
