# Generated by Django 5.2.2 on 2026-07-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_message_image_alter_message_texte'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='latitude_livraison',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='longitude_livraison',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='plat',
            name='plat_du_jour_le',
            field=models.DateField(blank=True, null=True),
        ),
    ]
