# Generated by Django 5.2.2 on 2026-07-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_adresselivraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='code_confirmation',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
