# Generated by Django 5.2.2 on 2026-07-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_livraison_code_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='frais_livraison',
            field=models.DecimalField(decimal_places=0, default=500, max_digits=10),
        ),
    ]
