# Generated by Django 5.2.2 on 2026-07-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_plat_frais_livraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='retraitfonds',
            name='payout_message',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='retraitfonds',
            name='payout_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
