# Generated by Django 5.2.2 on 2026-07-13 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_retraitfonds_payout_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='prix_reservation',
            field=models.DecimalField(decimal_places=0, default=5000, max_digits=10),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('date_reservation', models.DateTimeField()),
                ('nombre_personnes', models.PositiveSmallIntegerField(default=1)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('prix', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('code', models.CharField(blank=True, max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.restaurantprofile')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='core.transaction')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Photo'), ('video', 'Vidéo')], default='image', max_length=10)),
                ('fichier', models.FileField(upload_to='galerie/')),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='core.restaurantprofile')),
            ],
            options={
                'verbose_name': 'Média restaurant',
                'verbose_name_plural': 'Médias restaurant',
                'ordering': ['ordre', '-created_at'],
            },
        ),
    ]
