# Generated by Django 5.2.2 on 2026-07-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_restaurantprofile_prix_reservation_reservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='paiement_confirme',
            field=models.BooleanField(default=True),
        ),
    ]
