# Generated by Django 5.2.2 on 2026-07-19 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_commande_paiement_confirme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('publiee', 'Publiée'), ('refusee', 'Refusée')], default='publiee', max_length=20)),
                ('supprime_par', models.CharField(blank=True, choices=[('', 'Active'), ('client', 'Supprimée par le client'), ('restaurant', 'Supprimée par le restaurant')], default='', max_length=20)),
                ('supprime_le', models.DateTimeField(blank=True, null=True)),
                ('points_attribues', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL)),
                ('plat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='core.plat')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='core.restaurantprofile')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicationCommentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('supprime_par', models.CharField(blank=True, choices=[('', 'Actif'), ('auteur', "Supprimé par l'auteur"), ('restaurant', 'Supprimé par le restaurant'), ('admin', "Supprimé par l'administrateur")], default='', max_length=20)),
                ('supprime_le', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_publications', to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='core.publication')),
            ],
            options={
                'verbose_name': 'Commentaire de publication',
                'verbose_name_plural': 'Commentaires de publication',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicationLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications_likees', to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.publication')),
            ],
            options={
                'verbose_name': 'Like de publication',
                'verbose_name_plural': 'Likes de publication',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicationMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo')], default='image', max_length=10)),
                ('fichier', models.FileField(upload_to='publications/')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='core.publication')),
            ],
            options={
                'verbose_name': 'Média de publication',
                'verbose_name_plural': 'Médias de publication',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['restaurant', 'statut', 'supprime_par'], name='core_public_restaur_d67c81_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['-created_at'], name='core_public_created_6c64c2_idx'),
        ),
        migrations.AddIndex(
            model_name='publicationcommentaire',
            index=models.Index(fields=['publication', 'supprime_par'], name='core_public_publica_9b10c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='publicationlike',
            unique_together={('publication', 'client')},
        ),
    ]
