# Generated by Django 5.2.2 on 2026-07-19 18:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def attribuer_graines(apps, schema_editor):
    """Donne une graine DISTINCTE à chaque utilisateur existant.

    Sans cela, l'ajout de colonne applique la même valeur par défaut à toutes
    les lignes déjà en base : tous les utilisateurs partageraient la même
    graine et verraient donc exactement le même ordre dans le fil.
    """
    User = apps.get_model('core', 'User')
    for utilisateur in User.objects.all().only('id'):
        User.objects.filter(pk=utilisateur.pk).update(feed_seed=uuid.uuid4())


def annuler_graines(apps, schema_editor):
    """Rien à défaire : la colonne est supprimée par l'opération inverse."""


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_publication_publicationcommentaire_publicationlike_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrageFidelite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_publication_validee', models.PositiveIntegerField(default=5)),
                ('points_par_like', models.PositiveIntegerField(default=1)),
                ('points_par_commentaire', models.PositiveIntegerField(default=2)),
                ('points_par_unite', models.PositiveIntegerField(default=100, help_text='Nombre de points valant « valeur_unite » FCFA.')),
                ('valeur_unite', models.PositiveIntegerField(default=500, help_text='Réduction en FCFA obtenue pour « points_par_unite » points.')),
                ('seuil_minimum_conversion', models.PositiveIntegerField(default=100, help_text='Points minimum pour pouvoir convertir.')),
                ('reduction_max_pourcentage', models.PositiveIntegerField(default=30, help_text='Plafond de la réduction, en % du total de la commande.')),
                ('seuil_bronze', models.PositiveIntegerField(default=0)),
                ('seuil_argent', models.PositiveIntegerField(default=500)),
                ('seuil_or', models.PositiveIntegerField(default=2000)),
                ('actif', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramétrage fidélité',
                'verbose_name_plural': 'Paramétrage fidélité',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='feed_seed',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='points_solde',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(attribuer_graines, annuler_graines),
        migrations.CreateModel(
            name='MouvementPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField()),
                ('motif', models.CharField(choices=[('publication_validee', 'Publication validée'), ('like_recu', 'Like reçu'), ('commentaire_recu', 'Commentaire reçu'), ('depense_commande', 'Réduction utilisée'), ('annulation', 'Annulation'), ('ajustement', 'Ajustement manuel')], max_length=30)),
                ('source_type', models.CharField(blank=True, default='', max_length=20)),
                ('source_id', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mouvement de points',
                'verbose_name_plural': 'Mouvements de points',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', '-created_at'], name='core_mouvem_client__588034_idx')],
                'unique_together': {('client', 'motif', 'source_type', 'source_id')},
            },
        ),
    ]
