# Generated by Django 5.2.2 on 2026-07-19 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_parametragefidelite_user_feed_seed_user_points_solde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='points_utilises',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commande',
            name='reduction_points',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
