# Generated by Django 5.2.2 on 2026-07-20 12:25

import core.medias_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_commande_points_utilises_commande_reduction_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='apercu',
            field=models.ImageField(blank=True, null=True, upload_to=core.medias_utils.chemin_apercu),
        ),
        migrations.AddField(
            model_name='plat',
            name='flou',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='platimage',
            name='apercu',
            field=models.ImageField(blank=True, null=True, upload_to=core.medias_utils.chemin_apercu),
        ),
        migrations.AddField(
            model_name='platimage',
            name='flou',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='publicationmedia',
            name='apercu',
            field=models.ImageField(blank=True, null=True, upload_to=core.medias_utils.chemin_apercu),
        ),
        migrations.AddField(
            model_name='publicationmedia',
            name='flou',
            field=models.TextField(blank=True, default=''),
        ),
    ]
