# Generated by Django 5.2.2 on 2026-07-20 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_plat_apercu_plat_flou_platimage_apercu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementInclus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex. « Servi avec du pain »', max_length=120)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements_inclus', to='core.plat')),
            ],
            options={
                'verbose_name': 'Élément inclus',
                'verbose_name_plural': 'Éléments inclus',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GroupeComplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex. « Accompagnement », « Boisson »', max_length=80)),
                ('obligatoire', models.BooleanField(default=False)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes_complements', to='core.plat')),
            ],
            options={
                'verbose_name': 'Groupe de compléments',
                'verbose_name_plural': 'Groupes de compléments',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OptionComplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('supplement', models.DecimalField(decimal_places=0, default=0, help_text='0 = offert. Sinon, montant ajouté au prix du plat.', max_digits=12)),
                ('disponible', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.groupecomplement')),
            ],
            options={
                'verbose_name': 'Option de complément',
                'verbose_name_plural': 'Options de complément',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChoixLigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe_nom', models.CharField(max_length=80)),
                ('option_nom', models.CharField(max_length=80)),
                ('supplement', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix', to='core.lignecommande')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.optioncomplement')),
            ],
            options={
                'verbose_name': 'Choix de complément',
                'verbose_name_plural': 'Choix de compléments',
                'ordering': ['id'],
            },
        ),
    ]
