# Generated by Django 5.2.2 on 2026-07-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_elementinclus_groupecomplement_optioncomplement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='note_cache',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
