# Generated by Django 5.2.2 on 2026-07-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_restaurantprofile_note_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='livraison_libre',
            field=models.BooleanField(default=False),
        ),
    ]
