# Generated by Django 5.2.2 on 2026-08-08 00:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_transaction_provider_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banniere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_interne', models.CharField(max_length=100)),
                ('badge', models.CharField(blank=True, max_length=40)),
                ('titre', models.TextField()),
                ('sous_titre', models.CharField(blank=True, max_length=200)),
                ('texte_couleur', models.CharField(default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator(message='Couleur invalide — format attendu : #RRGGBB', regex='^#[0-9a-fA-F]{6}$')])),
                ('bouton_texte_couleur', models.CharField(default='#f26a1b', max_length=7, validators=[django.core.validators.RegexValidator(message='Couleur invalide — format attendu : #RRGGBB', regex='^#[0-9a-fA-F]{6}$')])),
                ('bouton_fond_couleur', models.CharField(default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator(message='Couleur invalide — format attendu : #RRGGBB', regex='^#[0-9a-fA-F]{6}$')])),
                ('fond_type', models.CharField(choices=[('image', 'Image'), ('couleur', 'Couleur unie'), ('degrade', 'Dégradé')], default='image', max_length=10)),
                ('fond_image', models.ImageField(blank=True, null=True, upload_to='bannieres/fond/')),
                ('fond_couleur', models.CharField(default='#1f8a4c', max_length=7, validators=[django.core.validators.RegexValidator(message='Couleur invalide — format attendu : #RRGGBB', regex='^#[0-9a-fA-F]{6}$')])),
                ('fond_degrade_debut', models.CharField(default='#f7891b', max_length=7, validators=[django.core.validators.RegexValidator(message='Couleur invalide — format attendu : #RRGGBB', regex='^#[0-9a-fA-F]{6}$')])),
                ('fond_degrade_fin', models.CharField(default='#f2611b', max_length=7, validators=[django.core.validators.RegexValidator(message='Couleur invalide — format attendu : #RRGGBB', regex='^#[0-9a-fA-F]{6}$')])),
                ('image_droite', models.ImageField(blank=True, null=True, upload_to='bannieres/droite/')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bannieres', to='core.plat')),
            ],
            options={
                'verbose_name': 'Bannière',
                'verbose_name_plural': 'Bannières',
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
