# Generated by Django 5.2.2 on 2026-08-28 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_banniere'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrageLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pourcentage_livreur', models.PositiveIntegerField(default=70, help_text='Part du livreur sur les frais de livraison, en %.')),
                ('seuil_paiement_auto', models.PositiveIntegerField(default=5000, help_text='Solde livreur (FCFA) déclenchant un versement automatique.')),
                ('delai_relance_minutes', models.PositiveIntegerField(default=20, help_text='Minutes avant de remettre au pool une mission prise mais pas démarrée.')),
                ('max_abandons', models.PositiveIntegerField(default=3, help_text="Nombre d'abandons sur la fenêtre avant désactivation automatique.")),
                ('fenetre_abandons_jours', models.PositiveIntegerField(default=7, help_text='Fenêtre glissante (jours) sur laquelle on compte les abandons.')),
                ('actif', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramétrage livraison',
                'verbose_name_plural': 'Paramétrage livraison',
            },
        ),
        migrations.AddField(
            model_name='commande',
            name='frais_livraison',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='commande',
            name='part_livreur',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='livraison',
            name='confirmee_par',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='livraison',
            name='motif_sans_code',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='user',
            name='paiement_numero',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='paiement_operateur',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('assignee', 'Assignée'), ('en_collecte', 'En collecte'), ('en_livraison', 'En livraison'), ('livree', 'Livrée'), ('livree_sans_code', 'Livrée — à valider'), ('echec', 'Échec')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('paiement_client', 'Paiement Client'), ('commission_eeuez', 'Commission plateforme'), ('reversement_restaurant', 'Reversement Restaurant'), ('gain_livreur', 'Gain livreur')], max_length=30),
        ),
        migrations.CreateModel(
            name='AbandonLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(blank=True, max_length=250)),
                ('auto', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abandons', to='core.commande')),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abandons_livraison', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abandon de livraison',
                'verbose_name_plural': 'Abandons de livraison',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppareilPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expo_token', models.CharField(max_length=255, unique=True)),
                ('plateforme', models.CharField(blank=True, choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appareils_push', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appareil push',
                'verbose_name_plural': 'Appareils push',
            },
        ),
        migrations.CreateModel(
            name='PaiementLivreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('operateur', models.CharField(choices=[('mtn_money', 'MTN Money'), ('orange_money', 'Orange Money')], default='mtn_money', max_length=20)),
                ('numero', models.CharField(blank=True, max_length=50)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('paye', 'Payé'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('payout_reference', models.CharField(blank=True, max_length=100)),
                ('payout_message', models.CharField(blank=True, max_length=250)),
                ('auto', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_livreur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement livreur',
                'verbose_name_plural': 'Paiements livreurs',
                'ordering': ['-created_at'],
            },
        ),
    ]
