# Generated by Django 5.2.2 on 2026-08-30 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_backfill_frais_livraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametragelivraison',
            name='coefficient_distance_routiere',
            field=models.DecimalField(decimal_places=2, default=1.3, help_text="Multiplicateur appliqué à la distance à vol d'oiseau pour estimer le trajet routier.", max_digits=4),
        ),
        migrations.CreateModel(
            name='PalierLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jusqu_a_km', models.DecimalField(decimal_places=1, help_text='Borne haute de la tranche, en km (incluse).', max_digits=5)),
                ('prix', models.DecimalField(decimal_places=0, help_text='Frais de livraison pour cette tranche, en FCFA.', max_digits=10)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paliers_livraison', to='core.restaurantprofile')),
            ],
            options={
                'verbose_name': 'Palier de livraison',
                'verbose_name_plural': 'Paliers de livraison',
                'ordering': ['jusqu_a_km'],
                'unique_together': {('restaurant', 'jusqu_a_km')},
            },
        ),
    ]
