# Generated by Django 5.2.2 on 2026-08-31 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_parametragelivraison_coefficient_distance_routiere_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commande_groupes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Groupe de commandes',
                'verbose_name_plural': 'Groupes de commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='commande',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='core.commandegroupe'),
        ),
        migrations.CreateModel(
            name='PaiementGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('mode_paiement', models.CharField(default='mtn_money', max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('complete', 'Complétée'), ('echouee', 'Échouée'), ('remboursee', 'Remboursée')], default='en_attente', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('provider_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groupe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='core.commandegroupe')),
            ],
            options={
                'verbose_name': 'Paiement de groupe',
                'verbose_name_plural': 'Paiements de groupe',
                'ordering': ['-created_at'],
            },
        ),
    ]
