# Generated by Django 5.2.2 on 2026-09-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_commandegroupe_commande_groupe_paiementgroupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='code_retrait',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='commande',
            name='emporter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='plats_a_emporter_actifs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='reservations_actives',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('en_preparation', 'En préparation'), ('prete', 'Prête'), ('en_livraison', 'En livraison'), ('livree', 'Livrée'), ('recuperee', 'Récupérée'), ('refusee', 'Refusée'), ('annulee', 'Annulée')], default='en_attente', max_length=30),
        ),
    ]
