# Generated by Django 5.2.2 on 2026-09-14 13:40

import core.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_commande_code_retrait_commande_emporter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartenaireWebhookConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('secret_chiffre', models.TextField()),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration webhook partenaire',
                'verbose_name_plural': 'Configurations webhook partenaires',
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evenement', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('statut_envoi', models.CharField(choices=[('en_attente', 'En attente'), ('envoye', 'Envoyé'), ('echec', 'Échec')], default='en_attente', max_length=10)),
                ('tentative', models.PositiveIntegerField(default=0)),
                ('dernier_code_http', models.PositiveIntegerField(blank=True, null=True)),
                ('derniere_erreur', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Envoi de webhook',
                'verbose_name_plural': 'Envois de webhooks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='commande',
            name='reference_externe',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_commercial', models.CharField(max_length=200)),
                ('raison_sociale', models.CharField(blank=True, max_length=200)),
                ('numero_rccm', models.CharField(blank=True, max_length=100, verbose_name='N° RCCM')),
                ('numero_contribuable', models.CharField(blank=True, max_length=100, verbose_name='NIU')),
                ('secteur', models.CharField(blank=True, max_length=150)),
                ('site_web', models.URLField(blank=True)),
                ('app_url', models.URLField(blank=True)),
                ('contact_nom', models.CharField(max_length=150)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_telephone', models.CharField(blank=True, max_length=30)),
                ('adresse', models.CharField(blank=True, max_length=300)),
                ('description_cas_usage', models.TextField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_verification', 'En vérification'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté'), ('suspendu', 'Suspendu')], default='en_attente', max_length=20)),
                ('motif_rejet', models.TextField(blank=True)),
                ('motif_suspension', models.TextField(blank=True)),
                ('verifie_le', models.DateTimeField(blank=True, null=True)),
                ('decide_le', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partenaire API',
                'verbose_name_plural': 'Partenaires API',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentKYB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('rccm', 'Registre du Commerce (RCCM)'), ('niu', "Attestation de Numéro d'Identifiant Unique (NIU)"), ('piece_identite_dirigeant', "Pièce d'identité du dirigeant"), ('autre', 'Autre document')], max_length=30)),
                ('fichier', models.FileField(storage=core.storage.DocumentKYBStorage(), upload_to='kyb/%Y/%m/')),
                ('statut', models.CharField(choices=[('soumis', 'Soumis'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='soumis', max_length=10)),
                ('commentaire', models.CharField(blank=True, max_length=300)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.partenaire')),
            ],
            options={
                'verbose_name': 'Document KYB',
                'verbose_name_plural': 'Documents KYB',
                'ordering': ['type_document'],
            },
        ),
        migrations.CreateModel(
            name='APICredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('secret_chiffre', models.TextField()),
                ('environnement', models.CharField(choices=[('sandbox', 'Sandbox'), ('live', 'Live')], default='sandbox', max_length=10)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('revoquee', 'Révoquée')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('derniere_utilisation', models.DateTimeField(blank=True, null=True)),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='core.partenaire')),
            ],
            options={
                'verbose_name': 'Identifiant API partenaire',
                'verbose_name_plural': 'Identifiants API partenaires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='commande',
            name='partenaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='core.partenaire'),
        ),
        migrations.AddConstraint(
            model_name='commande',
            constraint=models.UniqueConstraint(fields=('partenaire', 'reference_externe'), name='uniq_partenaire_reference_externe'),
        ),
        migrations.AddField(
            model_name='partenairewebhookconfig',
            name='partenaire',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webhook', to='core.partenaire'),
        ),
        migrations.AddField(
            model_name='webhookdelivery',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_deliveries', to='core.commande'),
        ),
        migrations.AddField(
            model_name='webhookdelivery',
            name='partenaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_deliveries', to='core.partenaire'),
        ),
    ]
