# Generated by Django 5.2.2 on 2026-09-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_partenairewebhookconfig_webhookdelivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicredential',
            name='mois_courant',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apicredential',
            name='requetes_mois_courant',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='plan',
            field=models.CharField(choices=[('decouverte', 'Découverte'), ('business', 'Business'), ('scale', 'Scale')], default='decouverte', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='identite_verifiee',
            field=models.BooleanField(default=False),
        ),
    ]
