# Generated by Django 5.2.2 on 2026-09-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_apicredential_mois_courant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='commission_partenaire',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='plan',
            field=models.CharField(choices=[('decouverte', 'Découverte'), ('croissance', 'Croissance'), ('business', 'Business'), ('scale', 'Scale')], default='decouverte', max_length=20),
        ),
    ]
