# Generated by Django 5.2.2 on 2026-09-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_commande_commission_partenaire_alter_partenaire_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenaire',
            name='mot_de_passe_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='pays',
            field=models.CharField(default='Cameroun', max_length=100),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='numero_contribuable',
            field=models.CharField(blank=True, max_length=100, verbose_name='NIU (ou équivalent local)'),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='numero_rccm',
            field=models.CharField(blank=True, max_length=100, verbose_name='N° RCCM (ou équivalent local)'),
        ),
    ]
