# Generated by Django 5.2.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_partenaire_mot_de_passe_hash_partenaire_pays_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='livraison_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='alerte_retard_envoyee',
            field=models.BooleanField(default=False),
        ),
    ]
