# Generated by Django 5.2.2 on 2026-09-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_restaurantprofile_livraison_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='paiement_confirme',
            field=models.BooleanField(default=False),
        ),
    ]
