# Generated by Django 5.2.2 on 2026-10-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_user_pays_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='type_plat',
            field=models.CharField(blank=True, choices=[('entree', 'Entrée'), ('resistance', 'Plat de résistance'), ('diner', 'Dîner'), ('dessert', 'Dessert'), ('boisson', 'Boisson')], max_length=20),
        ),
    ]
