# Generated by Django 5.2.2 on 2026-10-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_categories_sans_type_repas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneCiblage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('rayon_km', models.FloatField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zone de ciblage',
                'verbose_name_plural': 'Zones de ciblage',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='banniere',
            name='cercle_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banniere',
            name='cercle_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banniere',
            name='cercle_rayon_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banniere',
            name='cible_pays',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='banniere',
            name='cible_villes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='banniere',
            name='cible_zones',
            field=models.ManyToManyField(blank=True, related_name='bannieres', to='core.zoneciblage'),
        ),
    ]
