# Generated by Django 5.2.2 on 2026-10-10 16:05

from django.db import migrations, models


def preremplir(apps, schema_editor):
    """Catégories existantes : icône déduite du nom + ordre = ordre d'ancienneté."""
    from core.categories_icones import CLES_ICONES, suggerer_icone
    Categorie = apps.get_model('core', 'Categorie')
    for i, cat in enumerate(Categorie.objects.order_by('id')):
        if cat.icone not in CLES_ICONES:
            cat.icone = suggerer_icone(cat.nom)
        cat.ordre = i
        cat.save(update_fields=['icone', 'ordre'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_banniere_ciblage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'ordering': ['ordre', 'id'], 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AddField(
            model_name='categorie',
            name='icone_image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/icones/'),
        ),
        migrations.AddField(
            model_name='categorie',
            name='icone_type',
            field=models.CharField(choices=[('icone', 'Icône'), ('image', 'Image')], default='icone', max_length=10),
        ),
        migrations.AddField(
            model_name='categorie',
            name='image_presentation',
            field=models.ImageField(blank=True, null=True, upload_to='categories/presentation/'),
        ),
        migrations.AddField(
            model_name='categorie',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='categorie',
            name='ordre',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categorie',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(preremplir, migrations.RunPython.noop),
    ]
