# Generated by Django 5.2.2 on 2026-10-10 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_categorie_icones_presentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(choices=[('changement_mdp', 'Changement de mot de passe')], max_length=30)),
                ('code_hache', models.CharField(max_length=128)),
                ('essais', models.PositiveSmallIntegerField(default=0)),
                ('utilise', models.BooleanField(default=False)),
                ('expire_le', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Code de vérification',
                'verbose_name_plural': 'Codes de vérification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'objet', '-created_at'], name='core_codeve_user_id_011a52_idx')],
            },
        ),
    ]
