# Generated by Django 5.2.2 on 2026-10-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_code_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='supprime_par',
            field=models.CharField(blank=True, choices=[('', 'Active'), ('client', 'Supprimée par le client'), ('restaurant', 'Supprimée par le restaurant'), ('admin', "Masquée par l'administrateur")], default='', max_length=20),
        ),
    ]
