# Generated by Django 5.2.2 on 2026-10-10 20:06

import django.db.models.deletion
from django.db import migrations, models


def donnees_initiales(apps, schema_editor):
    """Reproduit la configuration actuelle : tout passe par CamerPay au Cameroun."""
    Agregateur = apps.get_model('core', 'Agregateur')
    Operateur = apps.get_model('core', 'Operateur')
    PaysPaiement = apps.get_model('core', 'PaysPaiement')
    RoutePaiement = apps.get_model('core', 'RoutePaiement')

    agregateurs = {}
    for code in ('camerpay', 'cinetpay', 'campay', 'pawapay'):
        agregateurs[code], _ = Agregateur.objects.get_or_create(code=code, defaults={'actif': code == 'camerpay'})

    operateurs = {}
    for ordre, (code, nom, couleur, fmt) in enumerate([
        ('mtn_momo', 'MTN Mobile Money', '#ffcc00', '6 7X XX XX XX'),
        ('orange_money', 'Orange Money', '#ff7900', '6 9X XX XX XX'),
        ('moov_money', 'Moov Money', '#0066b3', ''),
        ('wave', 'Wave', '#1dc8f2', ''),
        ('airtel_money', 'Airtel Money', '#e40000', ''),
        ('free_money', 'Free Money', '#cd1e25', ''),
    ]):
        operateurs[code], _ = Operateur.objects.get_or_create(
            code=code, defaults={'nom': nom, 'couleur': couleur, 'format_numero': fmt, 'ordre': ordre},
        )

    PaysPaiement.objects.get_or_create(pays_code='CM', defaults={'devise': 'XAF', 'indicatif': '237'})
    for op in ('mtn_momo', 'orange_money'):
        RoutePaiement.objects.get_or_create(
            pays_code='CM', ville='', ville_normalisee='', operateur=operateurs[op],
            agregateur=agregateurs['camerpay'], defaults={'priorite': 1},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_publication_masquee_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agregateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('camerpay', 'CamerPay'), ('cinetpay', 'CinetPay'), ('campay', 'Campay'), ('pawapay', 'PawaPay')], max_length=20, unique=True)),
                ('actif', models.BooleanField(default=False)),
                ('en_maintenance', models.BooleanField(default=False)),
                ('note_maintenance', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agrégateur de paiement',
                'verbose_name_plural': 'Agrégateurs de paiement',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AlerteAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('info', 'Information'), ('avertissement', 'Avertissement'), ('critique', 'Critique')], default='info', max_length=15)),
                ('categorie', models.CharField(choices=[('paiement', 'Paiements'), ('livraison', 'Livraisons'), ('securite', 'Sécurité'), ('systeme', 'Système')], default='systeme', max_length=15)),
                ('titre', models.CharField(max_length=160)),
                ('message', models.TextField(blank=True)),
                ('donnees', models.JSONField(blank=True, default=dict)),
                ('lue', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Alerte admin',
                'verbose_name_plural': 'Alertes admin',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DestinataireAlerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('niveau_minimum', models.CharField(choices=[('info', 'Information'), ('avertissement', 'Avertissement'), ('critique', 'Critique')], default='avertissement', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Destinataire d'alertes",
                'verbose_name_plural': "Destinataires d'alertes",
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Operateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=30, unique=True)),
                ('nom', models.CharField(max_length=60)),
                ('couleur', models.CharField(default='#f26a1b', max_length=7)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='operateurs/')),
                ('format_numero', models.CharField(blank=True, max_length=40)),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Opérateur Mobile Money',
                'verbose_name_plural': 'Opérateurs Mobile Money',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='PaysPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays_code', models.CharField(max_length=2, unique=True)),
                ('devise', models.CharField(default='XAF', max_length=3)),
                ('indicatif', models.CharField(blank=True, help_text='Ex. 237 (sans +)', max_length=5)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pays de paiement',
                'verbose_name_plural': 'Pays de paiement',
                'ordering': ['pays_code'],
            },
        ),
        migrations.AddField(
            model_name='paiementgroupe',
            name='agregateur',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='paiementgroupe',
            name='operateur',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='reservation',
            name='agregateur',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='operateur',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='transaction',
            name='agregateur',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='operateur',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='retraitfonds',
            name='mode_paiement',
            field=models.CharField(choices=[('mtn_money', 'MTN Money'), ('orange_money', 'Orange Money'), ('carte', 'Carte Bancaire'), ('especes', 'Espèces'), ('mobile_money', 'Mobile Money')], default='mtn_money', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='mode_paiement',
            field=models.CharField(choices=[('mtn_money', 'MTN Money'), ('orange_money', 'Orange Money'), ('carte', 'Carte Bancaire'), ('especes', 'Espèces'), ('mobile_money', 'Mobile Money')], default='especes', max_length=20),
        ),
        migrations.CreateModel(
            name='TentativePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=100)),
                ('objet', models.CharField(choices=[('commande', 'Commande'), ('groupe', 'Panier multi-restaurants'), ('reservation', 'Réservation')], max_length=15)),
                ('agregateur', models.CharField(db_index=True, max_length=20)),
                ('operateur', models.CharField(blank=True, max_length=30)),
                ('pays_code', models.CharField(blank=True, max_length=2)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('devise', models.CharField(default='XAF', max_length=3)),
                ('flux', models.CharField(blank=True, max_length=12)),
                ('statut', models.CharField(choices=[('echec_lancement', 'Échec du lancement'), ('en_attente', 'En attente'), ('complete', 'Payé'), ('echouee', 'Échoué'), ('remboursee', 'Remboursé')], db_index=True, default='en_attente', max_length=20)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=100)),
                ('erreur', models.CharField(blank=True, max_length=300)),
                ('duree_ms', models.PositiveIntegerField(default=0)),
                ('bascule', models.BooleanField(default=False, help_text="Lancée en secours après l'échec d'un autre agrégateur")),
                ('derniere_verification', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tentative de paiement',
                'verbose_name_plural': 'Tentatives de paiement',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agregateur', 'created_at'], name='core_tentat_agregat_7c739b_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoutePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays_code', models.CharField(max_length=2)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('ville_normalisee', models.CharField(blank=True, db_index=True, editable=False, max_length=100)),
                ('priorite', models.PositiveSmallIntegerField(default=1, help_text='1 = principal, 2 = premier secours…')),
                ('actif', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agregateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='core.agregateur')),
                ('operateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='core.operateur')),
            ],
            options={
                'verbose_name': 'Route de paiement',
                'verbose_name_plural': 'Routes de paiement',
                'ordering': ['pays_code', 'ville_normalisee', 'operateur__ordre', 'priorite'],
                'indexes': [models.Index(fields=['pays_code', 'ville_normalisee'], name='core_routep_pays_co_928150_idx')],
                'constraints': [models.UniqueConstraint(fields=('pays_code', 'ville_normalisee', 'operateur', 'agregateur'), name='route_paiement_unique')],
            },
        ),
        migrations.RunPython(donnees_initiales, migrations.RunPython.noop),
    ]
